Insert aviation messages to database
fmidev/aviation-message-archiver pull request #11
Opened 2021-06-08 10:04 UTC by kasarit

2021-06-15 08:11 UTC, petringo requested changes
In general this looks really good! Though I would still request to configure connection timeouts and implement proper recovery on errors. Unless I just didn't see it exists.

In additions to timeouts mentioned beside the code, I remember seeing a login timeout somewhere. It probably should be set if possible. Please check if there's anything else on this matter.

2021-06-16 12:59 UTC, kasarit commented on src/main/java/fi/fmi/avi/archiver/database/DatabaseAccess.java
> +        this.insertAviationMessage = new SimpleJdbcInsert(jdbcTemplate.getJdbcTemplate())
These timeouts are now set using the spring.jdbc.template.query-timeout property.

2021-06-17 08:11 UTC, petringo requested changes
Thanks, great work again! Sorry for being picky and seeing potential problems everywhere.

2021-06-17 08:11 UTC, petringo commented on src/test-integration/java/fi/fmi/avi/archiver/database/DatabaseAccessTest.java
> +public class DatabaseAccessTest {
Would there exist a reasonable way to test retry on both recoverable and non-recoverable database errors?

2021-06-17 08:38 UTC, kasarit commented on src/main/java/fi/fmi/avi/archiver/config/DataSourceConfig.java
> +        retryTemplateBuilder.infiniteRetry();
Definitely a good idea. Makes me more comfortable about using the infinite retry to begin with.

2021-06-17 11:17 UTC, petringo approved these changes
There it is now.

2021-06-17 11:18 UTC, merged